---
 - name: Configuracion de propiedades de jboss
   lineinfile: dest={{jboss_eap_home_path}}/bin/domain.conf insertafter="policy-permissions=true.\n" line={{ item }}
   with_items:
    - JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address={{ hostvars[inventory_hostname]['ansible_'+jboss_binding_interface].ipv4.address }}"
    - JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address.management={{ hostvars[inventory_hostname]['ansible_'+jboss_binding_management_interface].ipv4.address }}"
    - JAVA_OPTS="$JAVA_OPTS -Djboss.modules.metrics=true"
    - JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
    - JAVA_OPTS="$JAVA_OPTS -Djboss.domain.master.address={{ domain_master_address }}"

# - name: Respaldando host.xml
#  copy: remote_src=True  src={{jboss_eap_home_path}}/domain/configuration/host.xml dest={{jboss_eap_home_path}}/domain/configuration/host.xml.bak

# - name: Copiando host-slave.xml
#   copy: remote_src=True src={{jboss_eap_home_path}}/domain/configuration/host-slave.xml dest={{jboss_eap_home_path}}/domain/configuration/host.xml

 - name: Agregando binding
   replace:
     path: /opt/jboss-eap/domain/configuration/host.xml
     regexp: "127.0.0.1"
     replace: "{{ hostvars[inventory_hostname]['ansible_'+jboss_binding_interface].ipv4.address }}"

 - name: "Stop JBoss"
   service:
     name: "jboss-eap"
     state: stopped

 - name: "Start JBoss"
   service:
     name: "jboss-eap"
     state: started

 - name: Pausa 10 sec
   pause: 
     seconds: 10

 - name: Creando coneccion user/pass
   script: conexion.sh '{{ jboss_eap_home_path }}' '{{ hostvars[inventory_hostname]['ansible_'+jboss_binding_interface].ipv4.address }}' '{{ jboss_eap_connection_password }}'



