---
- name: Firewall inicio y activacion
  service: name=firewalld state=started enabled=yes
    
- name: Firewall settings 9999
  firewalld: zone=public port=9999/tcp permanent=true state=enabled

- name: Firewall settings 9990
  firewalld: zone=public port=9990/tcp permanent=true state=enabled

- name: Reload Firewall
  shell: firewall-cmd --reload


#- name: Abriendo puertos firewall
#  firewalld: 
#   port: "{{item.port}}"
#   permanent: true
#   state: enabled
#   immediate: true
#   with_items:
#    - {port: '9999/tcp'}
#    - {port: '9990/tcp'}
