---
 - name: Copiar parche {{jboss_eap_last_patch}} a TMP
   copy: src=../../../Installers/JBoss-EAP/{{ item }} dest=/tmp/{{ item }}
   with_items:
    - "{{ jboss_eap_last_patch }}"

 - name: Aplicar Parches
   command: chdir={{jboss_eap_home_path}}/bin/ ./jboss-cli.sh "patch apply /tmp/{{ item }} --override-all"
   with_items:
    - "{{ jboss_eap_last_patch }}"
