---
- name: Creando servidores
# command: chdir={{jboss_eap_home_path}}/bin/ ././jboss-cli.sh --controller={{ hostvars[inventory_hostname]['ansible_'+jboss_binding_interface].ipv4.address }}:9999 -c  --command="/host={{ host_controller_name }}:write-remote-domain-controller(host={{domain_master_address}},port=9999,username={{jboss_eap_connection_user}},security-realm=ManagementRealm)"

