---
# This playbook

- hosts: domaincontroller
  remote_user: root
  vars:
    jboss_service_name: jboss-eap
    jboss_eap_version: 7.1.0

  vars_files:
    - variables/jboss-eap-variables.yml

  roles:
    - create-jboss-user
    - jdk-install
    - eap-install-dependencies
    - eap-install-domain-from-jar
    - eap-domain-controller-configuration
    - eap-domain-service-configuration-rhel
    - eap-domain-controller-change-name
    - eap-domain-controller-remove-default-servers-and-groups
    - eap-domain-controller-create-new-profiles
    - eap-domain-controller-reload
    - eap-domain-controller-create-new-groups
    - eap-domain-controller-create-user-connection
    - eap-apply-patches
    - eap-domain-firewalld
